# Site wide configuration

title: Dr. Thomas E. Keller
description: It's a github page!
logo: # 120x120 px default image used for Twitter summary card
teaser: back-1.jpg # 400x250 px default teaser image used in image archive grid
locale: en
url: http://thomas-keller.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Dr. Thomas E. Keller
  email: "thomas.e.keller@gmail.com"
  twitter: "@tek_keller"
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: headshot_square.jpg # 160x160 px image for author byline
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
