# Site wide configuration

title: Thomas E. Keller
description: "A scientific programmer in the Tampa Bay"
logo: dragonfly_120x120.jpg
teaser: 400x250.gif
locale: en_US
url: http://thomas-keller.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Thomas Keller
  web: http://thomas-keller.github.io
  email: thomas.e.keller@gmail.com
  twitter: tek_keller
  bio: "Scientific progammer in the Tampa Bay who still thinks Evolution is pretty cool"
  avatar: headshot_square.jpg # 160x160 px image for author byline
  google:
    plus: 
    ad-client: 
    ad-slot: 
  disqus-shortname: tekeller


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
